profile = "custom"

[msbuild]
project = "ULT/ULT.csproj"
configuration = "Release"

[msbuild.properties]
PublishTrimmed = false
SelfContained = true
PublishSingleFile = true
PublishReadyToRun = true
IncludeNativeLibrariesForSelfExtract = true
EnableCompressionInSingleFile = true
DebugType = "none"

[nuget]
publish = false

[github]
user = "hikarosato"
repo = "ULT"

[[pack]]
rid = ["win-x64"]
kinds = ["zip"]
